### ISSUE TITLE
Implement the Transport Tracking module for the platform

### ISSUE THREAD

**Issue by tanmay4osme** [Hermit-Labs-Pvt-Ltd/TransportTracking#1]
- [x] push code to the repository.

- [x] refactor the codes for updated Gradle version.

- [x] Build the app.

- [ ] Refactor and check for the flaws.

- [ ] check the back-end working.
